-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2Zcr9h9kbAUi4zHi
SheBQ2tb/Ill9SY8nyDVqCXhplOgCgYIKoZIzj0DAQehRANCAAROGzRHMQMIcLzp
WYGcNKj3VHoD0fxJfotmhFDFkmOjQ3BQRlTbcYDfaYdlyOrtFBok4lF6gF7NSB8g
7NfHsroI
-----END PRIVATE KEY-----